openapi: 3.0.3
info:
  title: MSDS API
  version: 1.0.0
  description: |
    물질안전보건자료(MSDS) API 명세서
    
    ## 주요 기능
    - MSDS CRUD 작업 (생성, 조회, 수정, 삭제)
    - PDF 파일 업로드/다운로드
    - 추가자료 관리 (보호장구, 경고표지, 장소 등)
    - 검색 및 페이지네이션
    - 옵션 데이터 조회
    - 첨부파일 다운로드

servers:
  - url: http://localhost:5001
  - url: http://127.0.0.1:5001

paths:
  /healthz:
    get:
      summary: 헬스체크
      description: 서비스 상태를 확인하는 헬스체크 엔드포인트
      tags:
        - System
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok

  /api/msds:
    get:
      summary: MSDS 목록 조회 (페이지네이션 지원)
      description: |
        전체 MSDS 목록을 페이지네이션과 함께 반환합니다.
        detailed 파라미터로 첨부파일 정보 포함 여부를 선택할 수 있습니다.
      tags:
        - MSDS
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            default: 1
            minimum: 1
          description: 페이지 번호
        - in: query
          name: per_page
          schema:
            type: integer
            default: 12
            minimum: 1
            maximum: 100
          description: 페이지당 항목 수
        - in: query
          name: detailed
          schema:
            type: boolean
            default: false
          description: 상세 정보 포함 여부 (첨부파일 포함)
      responses:
        "200":
          description: 목록 반환
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: "#/components/schemas/MSDS"
                  page:
                    type: integer
                    example: 1
                  per_page:
                    type: integer
                    example: 12
                  total:
                    type: integer
                    example: 50
    post:
      summary: MSDS 생성
      description: 새로운 MSDS 레코드를 생성합니다.
      tags:
        - MSDS
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/MSDSCreate"
      responses:
        "201":
          description: 생성 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: MSDS created successfully
        "400":
          description: 잘못된 요청
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "mid is required"

  /api/msds/search:
    get:
      summary: MSDS 검색
      description: |
        키워드 기반으로 MSDS를 검색합니다.
        title, usage, mid 필드에서 검색이 가능합니다.
      tags:
        - MSDS
      parameters:
        - in: query
          name: q
          schema:
            type: string
          description: 검색 키워드
        - in: query
          name: page
          schema:
            type: integer
            default: 1
            minimum: 1
          description: 페이지 번호
        - in: query
          name: per_page
          schema:
            type: integer
            default: 12
            minimum: 1
            maximum: 100
          description: 페이지당 항목 수
      responses:
        "200":
          description: 검색 결과
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: "#/components/schemas/MSDS"
                  page:
                    type: integer
                    example: 1
                  per_page:
                    type: integer
                    example: 12
                  total:
                    type: integer
                    example: 5

  /api/msds/options:
    get:
      summary: 옵션 데이터 조회
      description: |
        MSDS 수정에 필요한 옵션 데이터를 조회합니다.
        용도, 장소, 경고표지, 보호장구 목록을 반환합니다.
      tags:
        - MSDS
      responses:
        "200":
          description: 옵션 데이터 반환
          content:
            application/json:
              schema:
                type: object
                properties:
                  usages:
                    type: array
                    items:
                      type: string
                    example: ["순수처리", "세정", "분석"]
                  locations:
                    type: array
                    items:
                      type: string
                    example: ["실험실", "창고", "공장"]
                  warnings:
                    type: array
                    items:
                      type: string
                    example: ["독성", "부식성", "인화성"]
                  protective:
                    type: array
                    items:
                      type: string
                    example: ["방독마스크", "고무장갑", "보호안경"]

  /api/msds/{mid}:
    get:
      summary: MSDS 상세 조회
      description: 특정 MSDS의 상세 정보와 첨부파일 목록을 조회합니다.
      tags:
        - MSDS
      parameters:
        - in: path
          name: mid
          required: true
          schema:
            type: string
          description: MSDS ID
      responses:
        "200":
          description: 상세 데이터
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MSDSDetail"
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: MSDS not found
    put:
      summary: MSDS 수정
      description: 기존 MSDS 정보를 수정합니다.
      tags:
        - MSDS
      parameters:
        - in: path
          name: mid
          required: true
          schema:
            type: string
          description: MSDS ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/MSDSUpdate"
      responses:
        "200":
          description: 수정 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: MSDS updated successfully
                  data:
                    $ref: "#/components/schemas/MSDSDetail"
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: MSDS not found
    delete:
      summary: MSDS 삭제
      description: MSDS를 삭제합니다.
      tags:
        - MSDS
      parameters:
        - in: path
          name: mid
          required: true
          schema:
            type: string
          description: MSDS ID
      responses:
        "200":
          description: 삭제 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: MSDS deleted successfully

  /api/msds/{mid}/pdf:
    get:
      summary: MSDS PDF 직접 다운로드
      description: MSDS PDF 파일을 직접 다운로드합니다.
      tags:
        - PDF
      parameters:
        - in: path
          name: mid
          required: true
          schema:
            type: string
          description: MSDS ID
      responses:
        "200":
          description: PDF 파일 반환
          content:
            application/pdf:
              schema:
                type: string
                format: binary
        "404":
          description: Not Found
    post:
      summary: MSDS PDF 업로드
      description: MSDS PDF 파일을 업로드합니다.
      tags:
        - PDF
      parameters:
        - in: path
          name: mid
          required: true
          schema:
            type: string
          description: MSDS ID
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                pdf_file:
                  type: string
                  format: binary
                  description: PDF 파일
      responses:
        "200":
          description: 업로드 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: PDF uploaded successfully
                  file_path:
                    type: string
                    example: pdfs/1750328210807_hydrochloric-acid-35.pdf
        "400":
          description: 잘못된 요청
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: No PDF file provided
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: MSDS not found
    delete:
      summary: MSDS PDF 삭제
      description: MSDS PDF 파일을 삭제합니다.
      tags:
        - PDF
      parameters:
        - in: path
          name: mid
          required: true
          schema:
            type: string
          description: MSDS ID
      responses:
        "200":
          description: 삭제 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: PDF deleted successfully
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: MSDS not found

  /api/msds/{mid}/download:
    get:
      summary: MSDS PDF 다운로드 (서명 URL)
      description: |
        Supabase Storage에 저장된 PDF 파일을 서명된 URL을 통해 다운로드합니다.
        강제 다운로드를 위해 download=1 쿼리 파라미터를 사용할 수 있습니다.
      tags:
        - PDF
      parameters:
        - in: path
          name: mid
          required: true
          schema:
            type: string
          description: MSDS ID
        - in: query
          name: download
          schema:
            type: string
          description: 강제 다운로드 옵션 (download=1)
      responses:
        "302":
          description: Supabase 서명된 URL로 리다이렉트
        "404":
          description: Not Found

  /api/msds/{mid}/attachment/{aid}:
    get:
      summary: 추가자료 다운로드
      description: |
        MSDS 추가자료(이미지)를 서명된 URL을 통해 다운로드합니다.
      tags:
        - Attachment
      parameters:
        - in: path
          name: mid
          required: true
          schema:
            type: string
          description: MSDS ID
        - in: path
          name: aid
          required: true
          schema:
            type: integer
          description: 추가자료 ID
      responses:
        "302":
          description: Supabase 서명된 URL로 리다이렉트
        "404":
          description: Not Found

  /api/msds/additional-info:
    get:
      summary: 추가자료 목록 조회
      description: |
        추가자료 목록을 조회합니다.
        mid, type 파라미터로 필터링할 수 있습니다.
      tags:
        - Additional Info
      parameters:
        - in: query
          name: mid
          schema:
            type: string
          description: 해당 MSDS ID로 필터
        - in: query
          name: type
          schema:
            type: string
          description: 추가자료 타입으로 필터 (0: 보호장구, 1: 장소, 2: 경고표지)
      responses:
        "200":
          description: 목록 반환
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/AdditionalInfo"
    post:
      summary: 추가자료 생성
      description: 새로운 추가자료를 생성합니다.
      tags:
        - Additional Info
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AdditionalInfoCreate"
      responses:
        "201":
          description: 생성 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: MSDS additional info created successfully
        "400":
          description: 잘못된 요청
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "aid is required"

  /api/msds/additional-info/{aid}:
    put:
      summary: 추가자료 수정
      description: 기존 추가자료 정보를 수정합니다.
      tags:
        - Additional Info
      parameters:
        - in: path
          name: aid
          required: true
          schema:
            type: string
          description: 추가자료 ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AdditionalInfoUpdate"
      responses:
        "200":
          description: 수정 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: MSDS additional info updated successfully
    delete:
      summary: 추가자료 삭제
      description: 추가자료를 삭제합니다.
      tags:
        - Additional Info
      parameters:
        - in: path
          name: aid
          required: true
          schema:
            type: string
          description: 추가자료 ID
      responses:
        "200":
          description: 삭제 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: MSDS additional info deleted successfully

components:
  schemas:
    MSDS:
      type: object
      properties:
        mid:
          type: string
          example: M0001
          description: MSDS 고유 ID
        title:
          type: string
          example: 염산 35%
          description: MSDS 제목
        usage:
          type: string
          nullable: true
          example: 순수처리
          description: 용도
        file_loc:
          type: string
          nullable: true
          example: pdfs/1750328210807_hydrochloric-acid-35.pdf
          description: PDF 파일 경로
        is_osh:
          type: integer
          enum: [0, 1]
          example: 1
          description: 산업안전보건법 적용 여부
        is_chr:
          type: integer
          enum: [0, 1]
          example: 1
          description: 화학물질관리법 적용 여부

    MSDSDetail:
      allOf:
        - $ref: "#/components/schemas/MSDS"
        - type: object
          properties:
            attachments:
              type: array
              items:
                $ref: "#/components/schemas/Attachment"
              description: 첨부파일 목록

    MSDSCreate:
      type: object
      required: [mid, title]
      properties:
        mid:
          type: string
          description: MSDS 고유 ID
        title:
          type: string
          description: MSDS 제목
        usage:
          type: string
          nullable: true
          description: 용도
        file_loc:
          type: string
          nullable: true
          description: PDF 파일 경로
        is_osh:
          type: integer
          enum: [0, 1]
          default: 0
          description: 산업안전보건법 적용 여부
        is_chr:
          type: integer
          enum: [0, 1]
          default: 0
          description: 화학물질관리법 적용 여부

    MSDSUpdate:
      type: object
      properties:
        title:
          type: string
          description: MSDS 제목
        usage:
          type: string
          nullable: true
          description: 용도
        file_loc:
          type: string
          nullable: true
          description: PDF 파일 경로
        is_osh:
          type: integer
          enum: [0, 1]
          description: 산업안전보건법 적용 여부
        is_chr:
          type: integer
          enum: [0, 1]
          description: 화학물질관리법 적용 여부

    AdditionalInfo:
      type: object
      properties:
        aid:
          type: string
          example: A20240801001
          description: 추가자료 고유 ID
        mid:
          type: string
          example: M0001
          description: 연결된 MSDS ID
        title:
          type: string
          example: 방독마스크
          description: 추가자료 제목
        type:
          type: integer
          nullable: true
          example: 0
          description: 타입 (0: 보호장구, 1: 장소, 2: 경고표지)
        file_loc:
          type: string
          nullable: true
          example: msds/prgear/방독마스크.png
          description: 파일 경로
        createdAt:
          type: string
          format: date-time
          nullable: true
          example: "2025-08-11T01:23:45Z"
          description: 생성일시

    Attachment:
      type: object
      properties:
        aid:
          type: string
          example: A20240801001
          description: 추가자료 고유 ID
        title:
          type: string
          example: 방독마스크
          description: 추가자료 제목
        type:
          type: integer
          example: 0
          description: 타입 (0: 보호장구, 1: 장소, 2: 경고표지)
        file_loc:
          type: string
          nullable: true
          example: msds/prgear/방독마스크.png
          description: 파일 경로
        createdAt:
          type: string
          format: date-time
          example: "2025-08-11T01:23:45Z"
          description: 생성일시

    AdditionalInfoCreate:
      type: object
      required: [aid, mid, title]
      properties:
        aid:
          type: string
          description: 추가자료 고유 ID
        mid:
          type: string
          description: 연결할 MSDS ID
        title:
          type: string
          description: 추가자료 제목
        type:
          type: integer
          nullable: true
          description: 타입 (0: 보호장구, 1: 장소, 2: 경고표지)
        file_loc:
          type: string
          nullable: true
          description: 파일 경로

    AdditionalInfoUpdate:
      type: object
      properties:
        title:
          type: string
          description: 추가자료 제목
        type:
          type: integer
          nullable: true
          description: 타입 (0: 보호장구, 1: 장소, 2: 경고표지)
        file_loc:
          type: string
          nullable: true
          description: 파일 경로

tags:
  - name: System
    description: 시스템 관련 API
  - name: MSDS
    description: MSDS 기본 CRUD 작업
  - name: PDF
    description: PDF 파일 관리
  - name: Additional Info
    description: 추가자료 관리
  - name: Attachment
    description: 첨부파일 다운로드
